Feature/footer completed
akai-org/onepage pull request #8
Opened 2017-04-19 17:35 UTC by Haradd

Could you check it out? :)

2017-04-20 21:37 UTC, marcinlawnik commented
Czy pliki .less też są potrzebne, skoro dodajemy scss? Jak na moje to albo jedne albo drugie.

2017-04-20 21:43 UTC, Haradd commented
Masz rację

2017-05-14 19:52 UTC, tomaszgil requested changes
Widzę kilka problemów:
- kolory nagłówków nie są jednakowe (powinny być #333)
- kolor tekstu i ikon podobnie - wszystko ma #666
- cała stopka jest przesunięta w prawo, a nie wyśrodkowana - owiń całość w jakiś container
- ikonom brakuje obwodów
- fonty są za duże
- cała strona traci responsywność dla rozmiarów < 600px

2017-05-24 11:00 UTC, tomaszgil approved these changes

2017-05-24 11:01 UTC, merged